### ISSUE TITLE
How to add Alert manager name for each instance

### ISSUE THREAD

**Issue by vivekbny** [cloudflare/unsee#248]
We have 3 Alert managers running in Prod/Preprod/QA, we would like to differentiate with specific names to it, Please let us know where to set Alertmanager names. Right now when we use @Alertmanager, we see the name as " default" 

The reason we use Unsee is to see all Alerts from 3 alertmanagers but now we are unable to differentiate alertmanager names as it displays everything as default. Please advise. Thanks

**Comment by roidelapluie** [comment]
```
alertmanager:
  interval: 60s
  servers:
    - name: "srv1"
      uri: "http://10.19.20.37:9093"
      timeout: 10s
      proxy: true
    - name: "srv2"
      uri: "http://10.19.20.162:9093"
      timeout: 10s
      proxy: true

```

srv1 and srv2 in my example.
