### ISSUE TITLE
[0.9.1] Silence on Proxied Alertmanagers returns 404

### ISSUE THREAD

**Issue by svenmueller** [cloudflare/unsee#250]
Hi,

I configured that requests from browsers to our Alertmanagers will be proxied via unsee. But when looking at the developer console when trying to create a new silence in the UI, i see that the POST request to the proxy-endpoint returns a 404. We are using unsee 0.9.1.

request:
```
POST https://unsee.mydomain.com/proxy/alertmanager/staging/api/v1/silences 404
```

snippet form the config:
```
...
servers:
  - name: test
    uri: https://username:password@alertmanager.mydomain.com
    timeout: 30s
    proxy: true
  ...
  listen:
    address: "0.0.0.0"
    port: 8080 # port in Docker container (we are running unsee in k8s)
    prefix: /
  ...
```

When triggering the silencing requests, i can see the following debug log:
```
time="2018-04-12T15:50:02Z" level=debug msg="[test] Proxy request for /api/v1/silences"
```
Any idea what causes the issue or how i can debug this?

Thx a lot,
Sven
